### PR TITLE
Add poster generating capabilities

### PR DESCRIPTION
**Pull request by pc-coholic**
This PR adds a small helper class/function to generate CWA-posters.

Two layouts are included - the official portrait one as well as a landscape-version which has been inspired by the first one.

Since I'm not very good at graphics stuff, this might not be the best way to achieve the desired result - so feel free to discard this PR if it's not up to your standards :-)

(Since I `ìsort`ed the imports of the files I touched with this PR, some sorting of the imports has occurred)

### CODE REVIEW

**Comment by pc-coholic** [comment]
Using the posters/trademarks of the CWA might also relate to https://github.com/corona-warn-app/cwa-event-qr-code/issues/8

Although since `cwa-event-qr-code` also ships the posters, and we're not advertising this library using the CWA-logo, I don't think this is really an issue here. But IANAL...

**Comment by MaZderMind** [comment]
Thank you very much! That's awesome!

I'd like to wait for the linked Issue to be settled before merging. I'd expect the CWA Crew to be quite responsive and quick.

**Comment by MaZderMind** [comment]
Regarding the Code I'd like to try to avoid the temp-file if possible. Don't know if it is though.

I would also like to see the poster Code in its own File. And while we're at it, i'd like to see "svgut" to be something recognizable. Bytes are cheap and IDEs do autocompletion quite well these days. Maybe "svg_utils"? Would you mind refactoring your PR like this?

**Comment by MaZderMind** [comment]
So the Discussion in corona-warn-app/cwa-event-qr-code#8 is resolved enough for me, but I still see the above mentioned problems with the code. If you don't mind I'll try to work them out.

**Comment by pc-coholic** [comment]
Sure, feel free to do so!

Earliest I can have a look is probably around Wednesday - so whatever works best for you :)

**Pull request merged**
